#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            clientId: 0oa1g1g1ko5F0Zhkh5d7
#            clientSecret: 2dc-NPFUIZzUk0A3Vuh9gXxtm4622agU53ouOeltcekppuAZBVk2VY5_Zfjj8xHy
#            scope: openid,profile,email
#
#        provider:
#          okta:
#            name: okta
#            authorizationUri: https://dev-66105866.okta.com/oauth2/default/v1/authorize
#            tokenUri: https://dev-66105866.okta.com/oauth2/default/v1/token
#            userInfoUri: https://dev-66105866.okta.com/oauth2/default/v1/userinfo
#            revokeTokenUri: https://dev-66105866.okta.com/oauth2/default/v1/revoke
